export const CORE_PERMISSIONS = [
  { name: 'View Users',              slug: 'users.view',              mainGroup: 'Users' },
  { name: 'Create Users',            slug: 'users.create',            mainGroup: 'Users' },
  { name: 'Update Users',            slug: 'users.update',            mainGroup: 'Users' },
  { name: 'Delete Users',            slug: 'users.delete',            mainGroup: 'Users' },
  { name: 'View Roles',              slug: 'roles.view',              mainGroup: 'Roles' },
  { name: 'Manage Roles',            slug: 'roles.manage',            mainGroup: 'Roles' },
  { name: 'View Permissions',        slug: 'permissions.view',        mainGroup: 'Roles' },
  { name: 'Manage Permissions',      slug: 'permissions.manage',      mainGroup: 'Roles' },
  { name: 'View Settings',           slug: 'settings.view',           mainGroup: 'Settings' },
  { name: 'Manage Settings',         slug: 'settings.manage',         mainGroup: 'Settings' },
  { name: 'View Stripe Secrets',     slug: 'secrets.stripe.view',     mainGroup: 'Secrets' },
  { name: 'Manage Stripe Secrets',   slug: 'secrets.stripe.manage',   mainGroup: 'Secrets' },
  { name: 'View SendGrid Secrets',   slug: 'secrets.sendgrid.view',   mainGroup: 'Secrets' },
  { name: 'Manage SendGrid Secrets', slug: 'secrets.sendgrid.manage', mainGroup: 'Secrets' },
  { name: 'View Twilio Secrets',     slug: 'secrets.twilio.view',     mainGroup: 'Secrets' },
  { name: 'Manage Twilio Secrets',   slug: 'secrets.twilio.manage',   mainGroup: 'Secrets' },
  { name: 'View SMTP Secrets',       slug: 'secrets.smtp.view',       mainGroup: 'Secrets' },
  { name: 'Manage SMTP Secrets',     slug: 'secrets.smtp.manage',     mainGroup: 'Secrets' },
  { name: 'View Logs',               slug: 'logs.view',               mainGroup: 'Logs' },
  { name: 'Export Logs',             slug: 'logs.export',             mainGroup: 'Logs' },
  { name: 'View Tickets',            slug: 'tickets.view',            mainGroup: 'Support' },
  { name: 'Manage Tickets',          slug: 'tickets.manage',          mainGroup: 'Support' },
  { name: 'Manage TMS Projects',     slug: 'tms.projects.manage',     mainGroup: 'TMS' },
  { name: 'Manage Products',         slug: 'tms.products.manage',     mainGroup: 'TMS' },
  { name: 'View API Tokens',   slug: 'security.tokens.view',   mainGroup: 'Security' },
  { name: 'Manage API Tokens', slug: 'security.tokens.manage', mainGroup: 'Security' },
  { name: 'View Organizations',   slug: 'orgs.view',   mainGroup: 'Organizations' },
  { name: 'Manage Organizations', slug: 'orgs.manage', mainGroup: 'Organizations' },
  { name: 'View Billing',          slug: 'billing.view', mainGroup: 'Billing' },
  { name: 'Manage Billing',        slug: 'billing.manage', mainGroup: 'Billing' },
  { name: 'Manage Approvals',      slug: 'approvals.manage', mainGroup: 'Approvals' },
] as const

export const CORE_SETTINGS = [
  { group: 'general',     name: 'App Name',         slug: 'general.app_name',              type: 'string',  value: 'RBAC App', isPublic: true,  options: [] },
  { group: 'general',     name: 'Logo URL',          slug: 'general.logo_url',              type: 'image',   value: '',         isPublic: true,  options: [] },
  { group: 'general',     name: 'Favicon URL',       slug: 'general.favicon_url',           type: 'image',   value: '',         isPublic: true,  options: [] },
  { group: 'appearance',  name: 'Theme Template',    slug: 'appearance.theme',              type: 'select',  value: 'default',  isPublic: true,  options: ['default','dark','ocean','slate','rose','forest'] },
  { group: 'appearance',  name: 'Color Mode',        slug: 'appearance.mode',               type: 'select',  value: 'light',    isPublic: true,  options: ['light','dark','system'] },
  { group: 'auth',        name: 'Session Timeout',   slug: 'auth.session_timeout',          type: 'number',  value: 60,         isPublic: false, options: [] },
  { group: 'auth',        name: 'Force MFA',         slug: 'auth.mfa_global',               type: 'boolean', value: false,      isPublic: false, options: [] },
  { group: 'email',       name: 'From Name',         slug: 'email.from_name',               type: 'string',  value: 'RBAC App', isPublic: false, options: [] },
  { group: 'email',       name: 'From Address',      slug: 'email.from_address',            type: 'string',  value: '',         isPublic: false, options: [] },
  { group: 'third_party', name: 'Stripe Enabled',    slug: 'third_party.stripe_enabled',    type: 'boolean', value: false,      isPublic: false, options: [] },
  { group: 'third_party', name: 'Stripe Public Key', slug: 'third_party.stripe_public_key', type: 'string',  value: '',         isPublic: false, options: [] },
  { group: 'third_party', name: 'SendGrid Enabled',  slug: 'third_party.sendgrid_enabled',  type: 'boolean', value: false,      isPublic: false, options: [] },
  { group: 'third_party', name: 'Twilio Enabled',    slug: 'third_party.twilio_enabled',    type: 'boolean', value: false,      isPublic: false, options: [] },
  { group: 'third_party', name: 'SMTP Host',         slug: 'third_party.smtp_host',         type: 'string',  value: '',         isPublic: false, options: [] },
  { group: 'third_party', name: 'SMTP Port',         slug: 'third_party.smtp_port',         type: 'number',  value: 587,        isPublic: false, options: [] },
] as const

export const CORE_SECRETS = [
  { group: 'stripe',   name: 'Stripe Secret Key',     slug: 'stripe.secret_key' },
  { group: 'stripe',   name: 'Stripe Webhook Secret', slug: 'stripe.webhook_secret' },
  { group: 'sendgrid', name: 'SendGrid API Key',       slug: 'sendgrid.api_key' },
  { group: 'twilio',   name: 'Twilio Auth Token',      slug: 'twilio.auth_token' },
  { group: 'twilio',   name: 'Twilio Account SID',     slug: 'twilio.account_sid' },
  { group: 'smtp',     name: 'SMTP Password',          slug: 'smtp.password' },
] as const
